Создает разметку главной страницы
htmlacademy-htmlcss/555-nerds-31 pull request #2
Opened 2021-05-22 21:14 UTC by EtelBogen

2021-05-24 06:21 UTC, Manyaka requested changes

2021-05-24 06:21 UTC, Manyaka commented on index.html
> +        наб. Реки Карповки,<br>
тоже пока сделай без бр, блок сам текст пернесёт

2021-05-24 06:21 UTC, Manyaka commented on index.html
> +      </p>
дивчики, а не параграфы, это же не текст

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +            <p>
никаких параграфов, всё дивчики.

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +            <p>
отсюда и далее всё поправь

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +                <input type="text" name="min-price" placeholder="0" value="0">
```suggestion
                <input type="number" name="min-price" placeholder="0" value="0">
```

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +                <input type="text" name="max-price" placeholder="15000" value="15000">
```suggestion
                <input type="number" name="max-price" placeholder="15000" value="15000">
```

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +        </ul>
это всё один блок сортировки. Ну и как мы обсудили в телеге - это ссылки

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +        </ul>
этож навигация

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +            <h3>Sedona</h3>
лишние заголовки, вон там ниже уже есть заголовок, который описывает этот блок

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +            <img src="https://via.placeholder.com/358x578" alt="Скриншот сайта Sedona" width="358" height="578">
альтики стереть

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +              <p>Информационный сайт<br>для туристов</p>
брчик убрать

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +              <button type="button">9 900 ₽</button>
это плашка с ценой

2021-05-24 06:21 UTC, Manyaka commented on catalog.html
> +            </div>
это всё нужно обернуть в ссылку

см в ТЗ: 

> 3.10. Карточка товара: название товара является ссылкой, клик по нему открывает модальное окно с демонстрацией товара. Модальное окно верстать не нужно.

2021-05-24 08:57 UTC, EtelBogen commented on index.html
> +      <!-- Тут ниже слайдер -->
Я подумала про это, если честно. Что он есть на хедере главной страницы. Меня смутило то, что в официальных материалах к занятию по разметке его поместили в майн. Вот тут: https://up.htmlacademy.ru/profession/frontender/11/htmlcss/module/2/item/12 
Поэтому я решила сделать разметку так, как создатели курса показывают. Хотя, конечно, слайдер по логике больше для хедера. Но только на главной странице. В каталоге его уже нет.

2021-05-24 09:00 UTC, EtelBogen commented on catalog.html
> +      <h1>Магазин готовых шаблонов</h1>
Аналогично предыдущему. По макету я хотела его сначала в хедер, но пример разбора материала говорит, что это майн: https://up.htmlacademy.ru/profession/frontender/11/htmlcss/module/2/item/12 
Что делать? Лучше в хедер?

2021-05-24 09:01 UTC, EtelBogen commented on catalog.html
> +          <img src="https://via.placeholder.com/160x65" width="160" height="65" alt="Логотип дизайн-студии «Нёрдс»">
Поняла

2021-05-24 09:04 UTC, EtelBogen commented on blank.html
> +<!DOCTYPE html>
Да, поняла!

2021-05-24 09:12 UTC, EtelBogen commented on index.html
> +        </tbody>
Переставить местами код или надо содержимое перетащить? (проценты станут заголовками)

2021-05-24 09:14 UTC, Manyaka commented on index.html
> +      <!-- Тут ниже слайдер -->
Потому что каталог - это внутренняя страница, они всегда отличаются от индекса

2021-05-24 09:18 UTC, Manyaka commented on index.html
> +        </tbody>
конечно код, содержимое то ты правильно распределила

2021-05-24 09:20 UTC, Manyaka commented on catalog.html
> +      <h1>Магазин готовых шаблонов</h1>
лучше в хедер. Я посмотрела в инете и там нет такого, что h1 должен быть в мейне. Хедер тем более как раз место для загловков, вообще-то :)))

2021-05-24 09:30 UTC, EtelBogen commented on catalog.html
> +        </ul>
По идее да, но я честно тупо сделала так, как показали на лекции и в примере:
https://up.htmlacademy.ru/profession/frontender/11/htmlcss/demos/5169#17

Как сделать? Обернуть тегом навигации или оставить, как показывали?

2021-05-24 10:15 UTC, EtelBogen commented on index.html
> +      </p>
Блин, а тут тоже — я делала верстку, как показали в лекции: https://up.htmlacademy.ru/profession/frontender/11/htmlcss/demos/5167#48
Там все подобные поля размечали параграфами (возможно, лекторы очень не любят дивы, ну очень).
Поменять лучше на дивы? Проверять-то потом будет другой случайный наставник, а не создатели курса...

2021-05-24 10:18 UTC, Manyaka commented on catalog.html
> +        </ul>
просто в нав обернуть

2021-05-24 10:20 UTC, Manyaka commented on index.html
> +      </p>
да я знаю про лекторов, лекторы к дивам очень хорошо относятся )))) это просто студенты перебзели, и дивов бояться как огня :)))
переделать на дивы.

2021-05-25 17:41 UTC, Manyaka requested changes

2021-05-25 17:41 UTC, Manyaka commented on catalog.html
> +        <input id="email" type="text" name="email" placeholder="email@example.com">
```suggestion
        <input id="email" type="email" name="email" placeholder="email@example.com">
```

2021-05-25 17:41 UTC, Manyaka commented on catalog.html
> +      <a href="blank.html">Напишите нам</a>
это кнопка, потому что ты со страницы не переходишь, а на этой же странице у тебя открывается попап

2021-05-25 17:41 UTC, Manyaka commented on catalog.html
> +              <span>9 900 ₽</span>
это плашка, спан - это инлайновый тег, который внутри текста или любого другого блока делает что-то  для мелкого куска. Здесь по дизайну видно, что это блок.
Есть варианты?

2021-05-25 17:41 UTC, Manyaka commented on index.html
> +          </tr>
`th` - это `thead` сокращенно. Если ты используешь теги `<thead>   <tbody>`, а их обычно никто не использует, но тк это не важно, есть они или нет, их браузер проставляет автоматом, то мне лично всё равно пишешь ты их или нет, главное правильно. Заголовки в заголовках, боди в боди.

2021-05-25 17:41 UTC, Manyaka commented on index.html
> +          <a href="https://htmlacademy.ru/intensive/htmlcss">
`target="_blank"` тут поставь везде, чтобы юзер не уходил с нашего сайта, когда кликает по сторонним ссылкам

2021-05-25 17:50 UTC, EtelBogen commented on index.html
> +          <a href="https://htmlacademy.ru/intensive/htmlcss">
Тут просто требования к данному проекту:

3.6. Логотип Академии в блоке с партнёрами ведёт на лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов».

Я сразу решила поставить ссылку, чтобы не забыть. Могу убрать и вставить потом. Как лучше сделать?

2021-05-25 17:56 UTC, Manyaka commented on index.html
> +          <a href="https://htmlacademy.ru/intensive/htmlcss">
набери в гугле таргет бланк

2021-05-25 17:58 UTC, EtelBogen commented on index.html
> +          </tr>
Так, я запуталась. Про использование тегов thead и tbody поняла. Можно просто не писать, меньше работы. 
Проценты надо обернуть тегом th? А то я тупо куски кода переставила.

2021-05-25 18:03 UTC, EtelBogen commented on catalog.html
> +              <span>9 900 ₽</span>
Либо p, либо div?

2021-05-25 18:07 UTC, Manyaka commented on index.html
> +          </tr>
Заголовки должны быть в тегах заголовков, тело таблицы - в теге тела таблицы.  Если ты не знаешь зачем теги thead и tbody, то просто не используй их. Я подумала, что ты про них прочла и поэтому использовала :)

2021-05-25 18:08 UTC, Manyaka commented on catalog.html
> +              <span>9 900 ₽</span>
да, выбери что хочешь, можно и так и так. Хотя тк только текст, то я склоняюсь к параграфу больше.

2021-05-25 18:23 UTC, Manyaka commented on catalog.html
> +      <a href="blank.html">Напишите нам</a>
Потому что у них другой проект. Или хочешь кинь ссылки мне на всё, тк я не помню есть ли там такое в барбершопе, я тогда тебе отвечу

2021-05-25 18:27 UTC, EtelBogen commented on catalog.html
> +      <a href="blank.html">Напишите нам</a>
Образец разметки главной страницы: https://up.htmlacademy.ru/profession/frontender/11/htmlcss/demos/5167#1
Макет: https://www.figma.com/file/Vfnr2w1gfXIDenMWhsBTop/HTML-1-%2F-%D0%91%D0%B0%D1%80%D0%B1%D0%B5%D1%80%D1%88%D0%BE%D0%BF?node-id=0%3A1

В макете в скрытых слоях отрисовано как попап.

2021-05-25 18:32 UTC, EtelBogen commented on index.html
> +          </tr>
Я читала как раз, да. Но я сейчас запуталась по самой таблице: 
Уровень самоотдачи/Соблюдение сроков/Минимальная предоплата — это заголовки, верно?
Проценты — это данные. 
Изначально все было как нужно в плане использования тегов.

Вопрос: я могу сначала же тогда тег tbody, а потом тег thead (и все что у них внутри) использовать? Чтобы не разворачивать стилями (что не особо и возможно, как я поняла).

2021-05-25 18:57 UTC, EtelBogen commented on index.html
> +          </tr>
В общем, я пока поправлю до более простого варианта. 

Но мне хочется понять, что ты имела в виду, когда сказала, что надо поменять местами код, так как содержимое верно распределено. Точнее как именно нужно было поменять этот самый код.

Просто везде написано, что thead используется до tbody. Поэтому я изначально сделала так разметку, по смыслу.

2021-05-25 19:01 UTC, Manyaka commented on index.html
> +          </tr>
У тебя было:
```
      <table>
        <caption>с 2004 года Любим точность во всем:</caption>
        <thead>
          <tr>
            <th>Уровень самоотдачи</th>
            <th>Соблюдение сроков</th>
            <th>Минимальная предоплата</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>146<sup>%</sup></td>
            <td>100<sup>%</sup></td>
            <td>50<sup>%</sup></td>
          </tr>
        </tbody>
      </table>
 ```

В дизайне:
![Снимок](https://user-images.githubusercontent.com/6417966/119553848-b0987600-bda4-11eb-9cb1-4683f5bfea3b.PNG)

тебе надо было поменять местами секцию заголовков целиком с секцией боди

2021-05-25 19:29 UTC, EtelBogen commented on index.html
> +          </tr>
Я просто смотрела в спецификации, что thead нельзя после tbody:
As a child of a table element, after any caption, and colgroup elements and before any tbody, tfoot, and tr elements, but only if there are no other thead elements that are children of the table element.

Я лучше на всякий случай просто не буду использовать, чтобы не ошибиться.

Я могу убрать эти теги, но оставить th с заголовками же, чтобы показать, что это именно заголовки статьи? 
`      <table>
        <caption>с 2004 года Любим точность во всем:</caption>
          <tr>
            <td>146<sup>%</sup></td>
            <td>100<sup>%</sup></td>
            <td>50<sup>%</sup></td>
          </tr>
          <tr>
            <th>Уровень самоотдачи</th>
            <th>Соблюдение сроков</th>
            <th>Минимальная предоплата</th>
          </tr>
      </table>`

Так можно?

2021-05-25 19:32 UTC, EtelBogen commented on index.html
> +          </tr>
Все, теперь улеглось в голове. Спасибо большое, так и поправлю!

2021-05-26 06:56 UTC, merged