Стилизация главной страницы
htmlacademy-htmlcss/555-nerds-31 pull request #5
Opened 2021-06-08 21:25 UTC by EtelBogen

1. Добавила классы в разметку главной страницы.
2. Подключила normalize.css
3. Подключила style.css

2021-06-10 05:20 UTC, Manyaka requested changes

2021-06-10 05:20 UTC, Manyaka commented on normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
положи его и другую цсс в свою папочку, чего загрязнять рут проекта

2021-06-10 05:20 UTC, Manyaka commented on normalize.css
> +
Убери стили, которые не нужны, тк в соотв с критерием: https://up.htmlacademy.ru/htmlcss/31/criteries#b12
> Вёрстка идентично отображается в последних версиях браузеров Chrome, Firefox, Safari

2021-06-10 05:20 UTC, Manyaka commented on index.html
> +        <button type="button"><span>Третий слайд</span></button>
классы спанам сделай нужные

2021-06-15 06:12 UTC, Manyaka requested changes

2021-06-15 06:12 UTC, Manyaka commented
![Снимок экрана 2021-06-15 в 08 49 42](https://user-images.githubusercontent.com/6417966/122001959-cc96a280-cdb9-11eb-96a3-1a9786a78eb5.jpg)

2021-06-15 06:13 UTC, Manyaka commented
![Снимок экрана 2021-06-15 в 08 56 23](https://user-images.githubusercontent.com/6417966/122001986-d91afb00-cdb9-11eb-8cea-10e63e977b44.jpg)

2021-06-15 06:13 UTC, Manyaka commented
![Снимок экрана 2021-06-15 в 08 57 55](https://user-images.githubusercontent.com/6417966/122002030-e801ad80-cdb9-11eb-8d01-e866440a3f3a.jpg)

для зеленой и желтой кнопки тоже

2021-06-15 06:13 UTC, Manyaka commented
![Снимок экрана 2021-06-15 в 09 11 36](https://user-images.githubusercontent.com/6417966/122002100-fc45aa80-cdb9-11eb-868c-23767373d392.jpg)

2021-06-15 06:14 UTC, Manyaka commented on css/style.css
> +  vertical-align: middle;
это зачем?

2021-06-15 16:40 UTC, EtelBogen commented on css/style.css
> +  font-family: "Roboto", Arial, sans-serif;
Roboto основной (из гугл-шрифтов), Arial как системный — как для Windows, так и для MacOS. 
А вот про всякие вариации Unix/Linux, например, я не подумала. И честно говоря, сейчас поискала и  не смогла найти, что сейчас со шрифтами на линуксе (самые распространенные). По идее Arial довольно часто входит в пакет. 

Что еще можно подключить? Helvetica Neue для MacOS, Lucida Grande для MacOS 8-9? Ubuntu для Убунту собственно?

2021-06-15 16:50 UTC, Manyaka commented on css/style.css
> +  font-family: "Roboto", Arial, sans-serif;
Для мака гельветику да и хватит одной гельветики, Nimbus Sans - что-то из этого для Линукса

2021-06-15 17:15 UTC, EtelBogen commented on css/style.css
> +
> ![Снимок экрана 2021-06-15 в 08 57 55](https://user-images.githubusercontent.com/6417966/122002030-e801ad80-cdb9-11eb-8d01-e866440a3f3a.jpg)
> 
> для зеленой и желтой кнопки тоже

Не понимаю, что нужно сделать :( По макету там белый цвет, при нажатии — прозрачность. Вроде все работает во всех браузерах, проверяла.

2021-06-15 17:22 UTC, EtelBogen commented on css/style.css
> +  vertical-align: middle;
Для выравнивания, но сейчас поняла, что оно тут не нужно, потому что и так будет. Удаляю.

2021-06-15 19:09 UTC, EtelBogen commented on css/style.css
> +  vertical-align: middle;
Как показали в примере: так оформлять, если у вас все кнопочки/ссылки одинаково и в таком стиле.
Наследование типа шрифта (не очень понятно, если он в body), ну font-weigth у всех кнопок одинаковый, как и line-height. vertical-align и text-align так показали оформлять. Еще раз заглянула в демку — там так же. 

Как лучше сделать?

2021-06-16 06:34 UTC, Manyaka commented on css/style.css
> +  vertical-align: middle;
почитай что делает `vertical-align: middle;` Комент относится к 50 строке. Вообще коменты в гитлабе относятся к той строке, под которой написаны, если не выделена область.

2021-06-17 07:16 UTC, Manyaka requested changes

2021-06-17 07:16 UTC, Manyaka commented on index.html
> +  </head>
подвинь head назад - это тебе так отбьютифаило?

2021-06-17 07:16 UTC, Manyaka commented on css/style.css
> +/* Как лучше? Так, как ниже, или повесить дополнительные классы на зеленую и желтую кнопки и по ним стилизовать? Я нашла вот такой вариант, все работает. Но я не знаю нюансы, нормально ли использоват
Лучше придумать им свои классы

2021-06-17 07:16 UTC, Manyaka commented on css/style.css
> +}
https://up.htmlacademy.ru/htmlcss/31/criteries#b12

напиши мне последние версии браузеров. Прямо циферки. А потом напиши мне для какого браузера у тебя сделаны плейсхолдеры

2021-06-17 07:16 UTC, Manyaka commented on css/style.css
> +}
а ещё напиши мне чем отличается плейсхолдер от введенного текста?

2021-06-17 16:43 UTC, EtelBogen commented on index.html
> +  </head>
Да, судя по всему.

2021-06-17 16:56 UTC, EtelBogen commented on css/style.css
> +}
Firefox 89.0.1
Chrome 91.0.4472.106
Safari 14.1.1

::placeholder — для Firefox 51 и более поздние, Chrome 57 и более поздние, Safari 10.1 и более поздние (ну и еще Edge 79 и более поздние и Opera 34 и более поздние);
::-webkit-input-placeholder — для Chrome 4-56,  Safari 5-10;
:-moz-placeholder и ::-moz-placeholder — для Firefox 4-50;
::-ms-input-placeholder —  для IE 10-11

В общем, меня переклинило :) что надо не только для последних версий Firefox, Chrome и Safari. Так что я нашла максимально охватывающие варианты через Caniuse и даже проверила на мамином старом ноуте ради интереса (работало). Увлеклась.

По критериям мне нужно только ::placeholder и поставить opacity 1 для корректного отображения в Firefox, потому что у него по дефолту стоит прозрачность. Без opacity 1 все отражалось не очень.

2021-06-17 17:19 UTC, Manyaka commented on css/style.css
> +}
да, точно. Хорошо, что ты увлеклась и раскопала старые варианты, если вдруг надо будет поддерживать старые браузеры, то ты знаешь что делать. И да, в ФФ надо всегда исправлять опасити - он плейсхолдеры стилизует по своему.

2021-06-18 07:49 UTC, merged