Сетка на гридах для главной страницы
htmlacademy-htmlcss/555-nerds-31 pull request #7
Opened 2021-06-27 19:50 UTC by EtelBogen

2021-06-29 12:17 UTC, Manyaka requested changes

2021-06-29 12:17 UTC, Manyaka commented on index.html
> +    <div class="center">
бессмысленный тег (и беспощадный). Тег - не класс.
Для начала, твоя идея: на тег header вешаем бг-цвет, тк он тянется на весь экран, а потом внутренним дивом задаем максимальную ширину хедеру и выравниваем его по-середине экрана. И для этого ты оборачиваешь всё в еще один див, вместо того, чтобы существующим тегам задать этот класс.
Это создает лишнюю обертку.
Надо использовать созданный тобой класс для центрирования (ну норм, можно сделать такой отдельный класс - это удобно) на уже существующей раскладке html.

2021-06-29 12:17 UTC, Manyaka commented on css/style.css
> +.main-navigation {
обрати внимание, что в главной навигации элементы выровнены вертикально по центру. Можно ли дописать это с помощью свойства для грид сетки?

2021-06-29 12:17 UTC, Manyaka commented on css/style.css
> +  justify-self: center;
вот тут ты правильно заметила, что по-горизонтали этот блок по-центру!

2021-06-29 12:17 UTC, Manyaka commented on css/style.css
> +  column-gap: 40px;
откуда взялось число 40?

2021-06-29 12:17 UTC, Manyaka commented on css/style.css
> +  column-gap: 40px;
Хотя к этому моменту, я уже увидела, что ты грид-гап взяла из сетки дизайнера. Внимание вопрос :))) А теперь объясни мне разницу между твоей сеткой и сеткой дизайнера и почему нельзя просто так взять грид-гап из диз-сетки и применить для своей?

2021-06-29 12:36 UTC, tachisis commented on css/style.css
>    line-height: 24px;
Я взяла по самому широкому элементу — карта внизу. Но кажется, до меня дошло, что там через фрейм будет бесконечная карта. А вот какого размера делать подложку из картинки карты? Она-то 1440 шириной.

Я поэтому взяла минималку 1440 и потом делала центрирование по остальной ширине элементов.

Если я возьму минимальную ширину по основным элементам, то мне на картинку с картой просто не вешать класс center? Ну чтобы ее не ужимало до 1160?

2021-06-29 17:16 UTC, EtelBogen commented on css/style.css
>    line-height: 24px;
Да, я брала ширину по самому широкому элементу — изображению карты внизу. И вот до меня только что дошло, что там, наверное, можно будет сделать бесконечную карту, как заливка хедера наверху. Так? 

Но у меня изображение из макета шириной 1440. По идее мне нужно его сделать подложкой, если вдруг карта не загрузится. Его просто не ограничивать по ширине до 1160?

А для класса center я как раз указала ширину 1160.

мне в итоге сделать и минимальную ширину, и по центрированию — 1160?

2021-06-29 17:23 UTC, EtelBogen commented on index.html
> +    <div class="center">
Поняла. 
Можно оставить цвет на хедере, а центрирование повесить? просто на два крупных элемента внутри — на навигацию и на слайдер, так?

2021-06-29 17:35 UTC, EtelBogen commented on css/style.css
> +  align-content: start;
Ок! Просто это вот тупо по лекции сделала. С теми же единицами прямо, мол задавайте align-content: start, чтобы начиналось все от начала. Хотя потом сразу сказали, что типа из-за min-content и 1fr хедер все время вверху, а футер всегда прижат. Но тогда действительно, зачем align-content: start... 
Можно спокойно убирать? А в каком случае это свойство потребуется?

2021-06-29 17:46 UTC, EtelBogen commented on css/style.css
> +  padding: 0;
Оу, должно было быть: padding: 0 10px; 
В лекции сказали, это чтобы «контент не прилипал к краям и вы должны будете тоже это сделать». Я десятку пикселей не дописала. Это использовать?

2021-06-29 17:52 UTC, EtelBogen commented on css/style.css
> +.main-navigation {
Да. Раз это выравнивания по оси блока, значит по идее надо использовать align-items: center?

2021-06-29 18:13 UTC, EtelBogen commented on css/style.css
> +  text-align: center;
Ой! justify-items: center же, да?

2021-06-29 18:57 UTC, EtelBogen commented on css/style.css
> +  column-gap: 40px;
Ну по идее сетка дизайнера — это разделение видимого пространства пропорционально. А в верстке по сути это не разделение пространства (потом это тоже так выглядит за счет задания нужных данных по отступам и прочим вещам), а выделение ячеек, которые потом выстраиваем в нужную структуру (управление потоком: как выстраивать, в каком порядке, чтобы получить сложные сетки). Не знаю, правильно ли формулирую, но механизм разный. Хотя в итоге внешне должно получится одно и тоже.

Почему нельзя взять. Честно? Не знаю. Не удобно считать отступы? Будет не удобно при адаптивной верстке?

2021-06-30 07:24 UTC, Manyaka commented on css/style.css
> +  column-gap: 40px;
Взять можно, но не тем способом, каким берешь ты. У диза сколько красных полосок? 12. Чтобы построить на гридах сетку как у диза надо что? `grid-template-columns: repeat(12, 1fr); column-gap: 40px` - вот так мы сделали сетку как диз сделал. Тогда наши элементы будут занимать сколько фракций - смотрим по дизу, например, цветные плашки будут занимать по 4 фракции. А у тебя другая сетка, у тебя всего лишь три колонки по 1 фракции, следовательно, нет смысла привязываться с гапу от диза.

2021-06-30 07:25 UTC, Manyaka commented on css/style.css
> +  text-align: center;
не, ну смотря что ты тут хочешь сделать (так то я вообще думала удалить это свойство за ненужностью)

2021-06-30 07:25 UTC, Manyaka commented on css/style.css
> +.main-navigation {
точно

2021-06-30 07:26 UTC, Manyaka commented on css/style.css
> +  padding: 0;
верстай, проверяй как получается, если будет внизу горизонтальная прокрутка - не пойдет

2021-06-30 07:27 UTC, Manyaka commented on css/style.css
> +  align-content: start;
А в каком случае это свойство потребуется? - ну вот и я хочу у тебя спросить, что надо было сделать, чтобы это свойство потребовалось?

2021-06-30 07:28 UTC, Manyaka commented on index.html
> +    <div class="center">
уже бы сделала давно и проверила, чем меня спрашивать :) я не браузер

2021-06-30 07:29 UTC, Manyaka commented on css/style.css
>    line-height: 24px;
Да, карта бесконечная, и она уже сейчас у тебя бесконечная. Ну вот и ответь мне как сделать 1160 и отцентрировать? А лучше не отвечай, а сделай.

2021-06-30 12:59 UTC, EtelBogen commented on css/style.css
> +  text-align: center;
Нужно, чтобы каждая картинка-логотип внутри ячейки грида находилась по центру. Потому что там они центрируются, задавать положение отступами слишком муторно.

2021-06-30 16:05 UTC, EtelBogen commented on css/style.css
> +  align-content: start;
Так, я почитала. Получается, что свойство  align-content в принципе нужно только тогда, когда строки и столбцы занимают область меньше, чем в контейнере сетки общем есть. Например, если бы были не относительные единицы, а четко заданные строки ну по 100пк. При этом контейнер сетки не 300пк, а там 600 пк. И тогда бы потребовалось определить положение строк индивидуально. При этом по умолчанию как раз действует align-content: start. Я так понимаю, что в арабском, например, стартовые линии были бы не сверху и слева, а сверху и справа.

2021-06-30 16:11 UTC, Manyaka commented on css/style.css
> +  align-content: start;
точно!

2021-07-02 06:39 UTC, Manyaka requested changes

2021-07-02 06:39 UTC, Manyaka commented on css/style.css
> +  min-width: 1180px;
нет, 1180 не прокатит. Это нарушает критерий, где минималка написана прямо цифрами какая должна быть: 1160пк. И в скобках указано на какой ширине проверять.

2021-07-02 06:39 UTC, Manyaka commented on css/style.css
> +  align-content: start;
что тут выравнивается по этой строке?

2021-07-02 14:40 UTC, EtelBogen commented on css/style.css
> +  align-content: start;
Оу, забыла убрать. Аналогично как делала грид для хедера-майн-футера, то сделала как в лекции.
Не нужно это свойство тут.

2021-07-02 15:22 UTC, merged